// FAQ

//GET ALL FAQ
export const GET_FAQ = "GET_FAQ";
export const GET_FAQ_SUCCESS = "GET_FAQ_SUCCESS";
export const GET_FAQ_FAILED = "GET_FAQ_FAILED";

// CREATE FAQ
export const ADD_NEW_FAQ = "ADD_NEW_FAQ";
export const ADD_NEW_FAQ_SUCCESS = "ADD_NEW_FAQ_SUCCESS";
export const ADD_NEW_FAQ_FAILED = "ADD_NEW_FAQ_FAILED";

//UPDATE
export const UPDATE_FAQ = "UPDATE_FAQ";
export const UPDATE_FAQ_SUCCESS = "UPDATE_FAQ_SUCCESS";
export const UPDATE_FAQ_FAILED = "UPDATE_FAQ_FAILED";

//DELETE
export const DELETE_FAQ = "DELETE_FAQ";
export const DELETE_FAQ_SUCCESS = "DELETE_FAQ_SUCCESS";
export const DELETE_FAQ_FAILED = "DELETE_FAQ_FAILED";

//GET BY ID

export const GET_FAQ_BY_ID = "GET_FAQ_BY_ID";
export const GET_FAQ_BY_ID_SUCCESS = "GET_FAQ_BY_ID_SUCCESS";
export const GET_FAQ_BY_ID_FAILED = "GET_FAQ_BY_ID_FAILED";

//GET FAQ_CATEGORY
export const GET_ALL_FAQ_CATEGORY = "GET_ALL_FAQ_CATEGORY";
export const GET_ALL_FAQ_CATEGORY_SUCCESS = "GET_ALL_FAQ_CATEGORY_SUCCESS";
export const GET_ALL_FAQ_CATEGORY_FAILED = "GET_ALL_FAQ_CATEGORY_FAILED";
