export const UPDATE_NOTIFICATION_KEYWORD = 'UPDATE_NOTIFICATION_KEYWORD';
export const UPDATE_PURCHASE_KEYWORD = 'UPDATE_PURCHASE_KEYWORD';
export const UPDATE_ADMIN_SEARCH_CUSTOMER_KEYWORD = 'UPDATE_ADMIN_SEARCH_CUSTOMER_KEYWORD';
